version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  admin:
    image: adminer
    ports:
      - 8080:8080
